repositories:
- name: jetstack
  url: https://charts.jetstack.io
- name: ingress-nginx
  url: https://kubernetes.github.io/ingress-nginx

releases:
- name: cert-manager
  chart: jetstack/cert-manager
  version: v1.10.1
  namespace: cert-manager
  createNamespace: true
  values:
  - cert-manager.values.yaml

- name: certmanager-issuers
  chart: ./certmanager-issuers-chart
  namespace: cert-manager
  needs:
  - cert-manager
  values:
  - ./certmanager-issuers-chart/values.yaml

- name: nginx-ingress
  chart: ingress-nginx/ingress-nginx
  version: 4.10.0
  namespace: default
  values:
  - nginx-ingress.values.yaml
